version: "3.9"

services:
  frontend:
    build: .
    container_name: dampecon-frontend
    image: dampecon-frontend:latest
    restart: unless-stopped
    ports:
      - "5173:5173"  # host:container
    environment:
      - NODE_ENV=production